[package]
name = "async_tcp_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge_async = {path = "../.."}
tokio = {version = "1.18.1", features=["io-util"]}
futures = "0.3.21"